#!/usr/bin/env python3
"""
Convert GSA question-bank .docx files into the site's test data file.

Each question in the docx is one table with rows:
  Question | <text>
  Type     | multiple_choice
  Option   | <text> | correct/incorrect   (x4)
  Solution | <text>
  Marks    | <positive> | <negative>

Usage:
  python tools/convert_docx.py "Free test Series/*.docx"  -o data/tests.js

Requires: pip install python-docx
"""
import argparse, glob, json, re, sys, os
from docx import Document


def slugify(name):
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s


def parse_docx(path):
    doc = Document(path)
    title = os.path.splitext(os.path.basename(path))[0].replace("_", " ")
    heading = [p.text.strip() for p in doc.paragraphs if p.text.strip()]
    sections = []  # (name, first_q, last_q) from headings like "SECTION A — ... [Questions 1–40]"
    for h in heading:
        m = re.match(r"SECTION\s+([A-Z])\s*[—-]\s*(.+?)\s*\[Questions\s+(\d+)\s*[–-]\s*(\d+)\]", h)
        if m:
            sections.append({"name": f"Section {m.group(1)}: {m.group(2).title()}",
                             "from": int(m.group(3)), "to": int(m.group(4))})
    if heading and not heading[0].startswith("SECTION"):
        title = heading[0].title().replace("Ongc", "ONGC").replace("Cbt", "CBT").replace("(Cbt)", "(CBT)")

    questions = []
    for t in doc.tables:
        q = {"options": [], "answer": None, "solution": "", "marks": 4, "negative": 1}
        for r in t.rows:
            cells = [c.text.strip() for c in r.cells]
            key = cells[0].lower() if cells else ""
            if key == "question":
                q["text"] = re.sub(r"^\d+\.\s*", "", cells[1])
            elif key == "option":
                q["options"].append(cells[1])
                if len(cells) > 2 and cells[2].lower() == "correct":
                    q["answer"] = len(q["options"]) - 1
            elif key == "solution":
                q["solution"] = re.sub(r"^Correct Answer:\s*[A-D]\)\s*[^.]*\.\s*", "", cells[1])
            elif key == "marks":
                try:
                    q["marks"] = float(cells[1]); q["negative"] = float(cells[2]) if len(cells) > 2 else 0
                except ValueError:
                    pass
        if q.get("text") and q["options"]:
            questions.append(q)

    for s in sections:
        s["from"] -= 1  # zero-based
    m = re.match(r"Geology Set\s*(\d+)\s*(\w+)", title, re.I)
    if m:
        title = f"Geology Mock Test — Set {m.group(1)} ({m.group(2).title()})"
    tid = "ongc-geologist-cbt" if title.startswith("ONGC") else slugify(title)
    return {
        "id": tid,
        "title": title,
        "description": "",
        "category": "Geology",
        "difficulty": "Hard" if "hard" in title.lower() else "Mixed",
        "durationMinutes": max(30, len(questions) * 2),
        "sections": sections,
        "questions": questions,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("patterns", nargs="+")
    ap.add_argument("-o", "--out", default="data/tests.js")
    a = ap.parse_args()
    files = sorted(f for p in a.patterns for f in glob.glob(p))
    if not files:
        sys.exit("No .docx files matched")
    tests = [parse_docx(f) for f in files]
    for t in tests:
        print(f"{t['id']}: {len(t['questions'])} questions, {len(t['sections'])} sections")
    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
    with open(a.out, "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/convert_docx.py — do not edit by hand; re-run the converter.\n")
        fh.write("window.GSA_BUILTIN_TESTS = ")
        json.dump(tests, fh, ensure_ascii=False, indent=1)
        fh.write(";\n")
    print("wrote", a.out)


if __name__ == "__main__":
    main()
