#!/usr/bin/env python3
"""Builds 'OPSC Geologist: Mock Test 1 (Paper II – Geology)' and appends it to data/tests.js + data/tests-index.js.
Pattern follows the OPSC Geologist written test (Paper II: objective, +2 / −0.5 per question)."""
import json, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (section, question, [options], correct index, solution)
Q = []
def q(sec, text, opts, ans, sol): Q.append((sec, text, opts, ans, sol))

S = "Geomorphology"
q(S, "A pediment is best described as a", ["gently sloping erosional bedrock surface at the foot of a mountain front in arid regions", "depositional fan of coarse debris at a canyon mouth", "steep rock face produced by faulting", "flat-topped residual hill capped by laterite"], 0, "Pediments are gently inclined erosional surfaces cut in bedrock at the base of retreating mountain fronts in arid/semi-arid climates; alluvial fans are the depositional counterpart.")
q(S, "Inselbergs rising abruptly from the plains of the Eastern Ghats are typically", ["residual hills left by differential weathering and erosion of resistant granitoid/charnockite", "volcanic necks", "fault scarps", "drumlins of a former ice sheet"], 0, "Inselbergs are erosional residuals (e.g., the charnockite/granite domes of Odisha–Andhra), produced by deep weathering and stripping of surrounding softer rock.")
q(S, "Which drainage pattern develops on a terrain of alternating hard and soft dipping strata?", ["Dendritic", "Trellis", "Radial", "Deranged"], 1, "Trellis drainage has long parallel streams along soft strata with short right-angle tributaries across hard ridges—typical of folded/dipping sedimentary belts.")
q(S, "The Mahanadi delta in Odisha is classified geomorphologically as", ["arcuate (wave-and-river influenced)", "bird's-foot", "cuspate", "estuarine with no sub-aerial delta"], 0, "The Mahanadi forms a lobate–arcuate delta reworked by waves and tides along the Bay of Bengal coast.")
q(S, "Laterite profiles are characteristically developed on", ["gently undulating plateaus under tropical monsoon climate with alternating wet–dry seasons", "steep slopes under temperate climate", "periglacial terrain", "active floodplains"], 0, "Laterite forms by intense leaching of silica and bases under seasonal tropical climates on stable, gently sloping surfaces (e.g., Odisha's laterite plateaus).")
q(S, "A knick point in a river's longitudinal profile most commonly indicates", ["rejuvenation (base-level fall or uplift) or a resistant lithology", "the river's mouth", "a meander cut-off", "maximum discharge"], 0, "Knick points mark breaks in slope where erosion is adjusting to a lowered base level or where the channel crosses resistant rock.")
q(S, "Chilika Lake is an example of a", ["brackish-water lagoon separated from the sea by a spit/barrier", "crater lake", "oxbow lake", "tectonic rift lake"], 0, "Chilika is Asia's largest brackish lagoon, bounded from the Bay of Bengal by a sandy barrier spit.")
q(S, "The Davisian 'cycle of erosion' stage dominated by broad floodplains, meanders and low relief is", ["youth", "maturity", "old age", "rejuvenation"], 2, "In Davis's scheme old-age landscapes are peneplains with sluggish meandering rivers; youth has V-valleys, maturity maximum relief.")

S = "Remote Sensing & GIS"
q(S, "Vegetation appears bright in standard false-colour composites (FCC) because", ["chlorophyll reflects strongly in the near-infrared, which is displayed as red", "green light is displayed as red", "water absorbs NIR", "soils emit thermal infrared"], 0, "In a standard FCC the NIR band is assigned to red; healthy vegetation has very high NIR reflectance, hence the red tone.")
q(S, "The NDVI is computed as", ["(NIR − Red) / (NIR + Red)", "(Red − NIR) / (Red + NIR)", "NIR / Red", "(Green − Red) / (Green + Red)"], 0, "NDVI = (NIR − R)/(NIR + R), ranging −1 to +1; dense vegetation ≈ 0.6–0.9.")
q(S, "Spatial resolution of a sensor refers to", ["the ground area represented by one pixel", "the number of spectral bands", "the revisit period", "the number of grey levels recorded"], 0, "Spatial = pixel footprint; spectral = bands; temporal = revisit; radiometric = grey levels (bit depth).")
q(S, "Which satellite series is Indian and widely used for geological mapping?", ["IRS / Resourcesat (LISS sensors)", "Landsat", "Sentinel", "SPOT"], 0, "ISRO's IRS series (LISS-III/IV, AWiFS on Resourcesat) is the Indian workhorse for land and geological mapping.")
q(S, "In a GIS, a buffer operation", ["creates a zone of specified distance around a feature", "joins two attribute tables", "converts raster to vector", "computes slope from a DEM"], 0, "Buffering generates proximity polygons—e.g., 500 m zones around faults or streams.")
q(S, "Shortwave infrared (SWIR) bands are especially useful in geology for", ["discriminating clay and carbonate minerals via absorption features near 2.2–2.35 µm", "measuring surface temperature", "detecting chlorophyll", "mapping bathymetry"], 0, "Al–OH (clays, ~2.2 µm) and CO₃ (carbonates, ~2.33 µm) absorptions lie in SWIR, exploited by ASTER/Sentinel-2 for alteration mapping.")
q(S, "A DEM is a", ["raster of elevation values", "vector line map of contours", "table of borehole logs", "thematic map of soils"], 0, "A Digital Elevation Model stores elevation per grid cell; slope, aspect and drainage are derived from it.")
q(S, "Hyperspectral sensors differ from multispectral mainly in", ["having hundreds of narrow contiguous bands", "higher spatial resolution", "operating only at night", "using active illumination"], 0, "Hyperspectral imaging (e.g., AVIRIS-NG) records 100s of narrow bands enabling mineral identification by spectral shape.")
q(S, "Which projection/coordinate system is most commonly used for Survey of India toposheets today?", ["UTM/WGS-84 (older sheets on Polyconic/Everest)", "Mercator/WGS-84", "Lambert Azimuthal", "Mollweide"], 0, "Open-series SoI maps use UTM on WGS-84; legacy toposheets were on Polyconic with the Everest datum.")
q(S, "Lineament analysis from satellite images primarily helps in", ["identifying fractures/faults controlling groundwater and mineralisation", "estimating rock age", "measuring metamorphic grade", "determining fossil content"], 0, "Lineaments are linear surface expressions of faults/joints—targets for groundwater and structurally controlled ore.")

S = "Structural Geology"
q(S, "The attitude of a plane is fully specified by", ["strike and dip (with dip direction)", "plunge alone", "trend alone", "pitch alone"], 0, "Strike + dip amount + dip direction define a plane; plunge/trend define a line; pitch (rake) is the angle of a line within a plane.")
q(S, "In a normal fault the hanging wall", ["moves down relative to the footwall", "moves up relative to the footwall", "moves horizontally only", "does not move"], 0, "Normal faults form under extension: hanging wall down. Reverse/thrust: hanging wall up.")
q(S, "An anticline whose axial plane is inclined and whose limbs dip in the same direction is", ["overturned fold", "symmetrical fold", "recumbent fold", "box fold"], 0, "Overturned folds have one inverted limb; both limbs dip the same way. Recumbent folds have near-horizontal axial planes.")
q(S, "Slaty cleavage is generally", ["parallel to the axial plane of the associated fold", "parallel to bedding", "perpendicular to the fold axis", "randomly oriented"], 0, "Axial-planar cleavage forms perpendicular to maximum shortening and is parallel to fold axial surfaces.")
q(S, "On a stereographic projection, poles to bedding from a cylindrical fold lie on", ["a great circle (π-girdle) whose pole is the fold axis", "a small circle", "a single point", "a straight line through the centre"], 0, "Poles to planes in a cylindrical fold define a π-girdle; its pole (β) gives the fold axis.")
q(S, "Boudinage develops in", ["a competent layer extended within a less competent matrix", "an incompetent layer under compression", "unconsolidated sediment", "igneous intrusions only"], 0, "Layer-parallel extension of a stiff layer in ductile matrix produces sausage-like boudins.")
q(S, "A klippe is", ["an erosional outlier of a thrust sheet surrounded by younger rocks", "a window exposing rocks beneath a thrust", "a vertical dyke", "a horst block"], 0, "Klippe = isolated remnant of the hanging wall of a thrust; fenster/window = hole eroded through the sheet.")
q(S, "Horsts and grabens are products of", ["extensional (normal) faulting", "strike-slip faulting", "thrusting", "folding"], 0, "Alternating uplifted (horst) and down-dropped (graben) blocks bounded by normal faults form in rifts.")
q(S, "Mohr–Coulomb failure criterion predicts that shear fractures form at an angle to σ₁ of about", ["30°", "45°", "60°", "90°"], 0, "Conjugate shear fractures typically form at ~30° to σ₁ (θ = 45° − φ/2 with φ ≈ 30°).")
q(S, "Mullions and rodding are examples of", ["linear structures", "planar structures", "unconformities", "primary sedimentary structures"], 0, "Lineations include mineral lineation, intersection lineation, mullions, rods, boudin axes and slickenlines.")
q(S, "An angular unconformity implies", ["tilting/folding and erosion of older strata before deposition of younger beds", "continuous deposition", "igneous intrusion", "metamorphism of the younger unit"], 0, "Angular unconformity: older beds deformed and eroded, then overlain by flat younger strata.")
q(S, "In the Sukinda valley of Odisha, the chromite-bearing ultramafic bodies occur as", ["a layered, folded sill-like complex within the Iron Ore Group / Singhbhum craton", "young volcanic flows", "Gondwana sediments", "Tertiary alluvium"], 0, "Sukinda ultramafics (dunite–peridotite–orthopyroxenite with chromitite seams) form a deformed layered body hosting ~95% of India's chromite.")

S = "Geodynamics"
q(S, "The Mohorovičić discontinuity separates", ["crust and mantle", "mantle and outer core", "outer and inner core", "lithosphere and asthenosphere"], 0, "Moho marks the crust–mantle boundary, identified by a jump in P-wave velocity (~6.5–7 to ~8 km/s).")
q(S, "Sea-floor spreading was confirmed chiefly by", ["symmetric magnetic anomaly stripes across mid-ocean ridges", "deep-sea trenches", "earthquake-free zones", "continental fossils"], 0, "Vine–Matthews–Morley (1963): alternating normal/reversed magnetisation stripes symmetric about ridges record spreading.")
q(S, "The Wadati–Benioff zone is", ["an inclined zone of earthquakes marking a subducting slab", "a zone of shallow ridge earthquakes", "the low-velocity zone", "the transition zone at 410 km"], 0, "Benioff zones dip beneath island arcs/continental margins to ~700 km, tracing the subducting plate.")
q(S, "S-waves do not travel through the outer core because", ["it is liquid", "it is too hot", "it is too dense", "it is iron-rich"], 0, "Shear waves need rigidity; the liquid outer core produces the S-wave shadow zone (>103° epicentral distance).")
q(S, "The Indian plate's collision with Eurasia began approximately", ["50–55 million years ago (Early Eocene)", "250 million years ago", "5 million years ago", "150 million years ago"], 0, "India–Asia collision initiated ~55–50 Ma, after rapid northward drift following Gondwana break-up.")
q(S, "Isostasy according to Airy's hypothesis assumes", ["uniform density crust with variable thickness (deep roots under mountains)", "variable density, uniform thickness", "no compensation", "a rigid lithosphere everywhere"], 0, "Airy: mountains have thick crustal roots; Pratt: density varies laterally with uniform compensation depth.")
q(S, "Transform faults at mid-ocean ridges", ["offset ridge segments with motion opposite to apparent offset between the segments", "are purely compressional", "occur only on continents", "produce deep-focus earthquakes"], 0, "Active slip on transform faults is confined between ridge segments and is opposite to the sense suggested by the offset.")
q(S, "Hotspot volcanic chains such as Hawaii–Emperor indicate", ["plate motion over a relatively fixed mantle plume", "subduction", "continental rifting", "ridge jumping"], 0, "Progressive ages along the chain record plate motion over a stationary plume; the bend marks a change in plate direction.")

S = "Stratigraphy"
q(S, "The oldest rocks of the Singhbhum craton (Older Metamorphic Group) are about", ["3.5 billion years old", "2.0 billion years", "570 million years", "65 million years"], 0, "The Singhbhum craton includes ~3.5–3.3 Ga OMG/OMTG and the ~3.3–3.1 Ga Singhbhum Granite.")
q(S, "The high-grade metamorphic belt forming much of coastal Odisha is the", ["Eastern Ghats Mobile Belt", "Aravalli Fold Belt", "Dharwar craton", "Shillong Plateau"], 0, "The EGMB (granulite facies khondalite, charnockite, leptynite) borders the Singhbhum and Bastar cratons.")
q(S, "'Khondalite' is a", ["garnet–sillimanite–graphite gneiss (metapelite) of granulite facies", "basaltic lava", "sandstone", "limestone"], 0, "Khondalite, named after the Khond region of Odisha, is a quartz–feldspar–garnet–sillimanite ± graphite granulite.")
q(S, "The Iron Ore Group (IOG) of Odisha–Jharkhand hosts banded iron formation of age roughly", ["Archaean (~3.1–2.6 Ga)", "Permian", "Cretaceous", "Pleistocene"], 0, "The IOG (Noamundi–Koira, Gorumahisani, Tomka–Daitari basins) is Archaean, containing BHJ/BHQ and high-grade hematite ore.")
q(S, "The Talcher Formation at the base of the Gondwana Supergroup is characterised by", ["glacial tillite and boulder beds", "coal seams", "red beds with dinosaur bones", "marine limestone"], 0, "Talcher (Late Carboniferous–Early Permian) begins with glacial diamictite/tillite recording Gondwana glaciation; coal is in the overlying Barakar/Karharbari.")
q(S, "Major coal seams of the Talcher and Ib-River coalfields belong mainly to the", ["Barakar Formation", "Panchet Formation", "Rajmahal Formation", "Vindhyan Supergroup"], 0, "Barakar (Early Permian) is the principal coal-bearing formation of peninsular Gondwana basins including Talcher and Ib valley.")
q(S, "The Deccan Traps erupted around", ["66 Ma, at the Cretaceous–Palaeogene boundary", "250 Ma", "20 Ma", "1 Ma"], 0, "Deccan flood basalts (~66–65 Ma) are linked to the Réunion plume and the K–Pg mass extinction.")
q(S, "Which Proterozoic basin lies largely in Odisha–Chhattisgarh and is known for diamonds and limestone?", ["Chhattisgarh (and Khariar/Ampani) basins", "Cuddapah basin", "Vindhyan basin", "Marwar basin"], 0, "The Chhattisgarh Supergroup and its outliers (Khariar, Ampani in Odisha) are Meso-Neoproterozoic cratonic basins.")
q(S, "The principle that undisturbed strata are younger upward is", ["superposition", "original horizontality", "cross-cutting relationships", "faunal succession"], 0, "Steno's law of superposition; original horizontality and lateral continuity are his other principles.")
q(S, "A lithostratigraphic unit of rank below Formation is", ["Member", "Group", "Supergroup", "System"], 0, "Hierarchy: Supergroup > Group > Formation > Member > Bed.")
q(S, "The Cuddapah Supergroup is of what age?", ["Palaeo-Mesoproterozoic", "Cambrian", "Jurassic", "Archaean"], 0, "Cuddapah basin sediments span ~1.9–1.0 Ga (Papaghni, Chitravati, Nallamalai groups).")
q(S, "Bauxite deposits of Panchpatmali (Koraput, Odisha) are developed over", ["khondalite of the Eastern Ghats", "Deccan basalt", "Gondwana sandstone", "Singhbhum granite"], 0, "East-coast bauxites (Panchpatmali, Gandhamardan) are lateritic caps on khondalite/charnockite plateaus.")
q(S, "The Permian–Triassic boundary in Gondwana basins is placed around the", ["Panchet Formation", "Talcher Formation", "Barakar Formation", "Kamthi Formation base"], 0, "The Panchet Formation (Early Triassic) overlies the Raniganj; the P–T boundary lies at/near its base.")
q(S, "Magnetostratigraphy is based on", ["reversals of the Earth's magnetic field recorded in rocks", "fossil content", "radiometric ages", "lithology"], 0, "Polarity reversals provide globally synchronous markers correlatable with the geomagnetic polarity time scale.")

S = "Palaeontology"
q(S, "Index (zone) fossils should ideally be", ["abundant, widespread, easily identifiable and of short stratigraphic range", "rare and long-ranging", "restricted to one locality", "soft-bodied"], 0, "Short vertical range + wide geographic spread make a fossil useful for correlation (e.g., ammonites, graptolites).")
q(S, "Glossopteris flora is characteristic of the", ["Permian Gondwana sequences", "Cambrian", "Jurassic of Laurasia", "Pleistocene"], 0, "Glossopteris (seed fern) dominated Permian Gondwana floras and is a key argument for continental drift.")
q(S, "Trilobites became extinct at the end of the", ["Permian", "Cambrian", "Cretaceous", "Devonian"], 0, "Trilobites, having declined through the Palaeozoic, disappeared in the end-Permian mass extinction (~252 Ma).")
q(S, "Ammonoids with highly complex (ammonitic) suture lines are typical of the", ["Mesozoic", "Cambrian", "Silurian", "Cenozoic"], 0, "Goniatitic sutures: Palaeozoic; ceratitic: Triassic; ammonitic (most complex): Jurassic–Cretaceous.")
q(S, "Stromatolites are", ["laminated structures built by cyanobacterial mats trapping sediment", "coral reefs", "burrows of worms", "fossil wood"], 0, "Stromatolites record microbial life back to ~3.5 Ga; abundant in Proterozoic carbonates (e.g., Vindhyan, Cuddapah).")
q(S, "Foraminifera are especially valuable in", ["biostratigraphy and palaeoenvironmental analysis of marine strata, including petroleum exploration", "dating Precambrian rocks", "dating igneous intrusions", "estimating metamorphic grade"], 0, "Planktonic and benthic forams give fine biozonation and palaeodepth/temperature information in Mesozoic–Cenozoic marine sections.")
q(S, "Dinosaur egg nests and bones in India are famously reported from the", ["Lameta Formation (Late Cretaceous) of central India", "Barakar Formation", "Siwalik Group", "Cuddapah Supergroup"], 0, "The Maastrichtian Lameta beds (Jabalpur, Bagh, Kheda) underlie Deccan Traps and yield titanosaur eggs and Rajasaurus.")
q(S, "The Siwalik Group is renowned for fossils of", ["Mio-Pliocene mammals (e.g., Sivapithecus, Stegodon)", "Cambrian trilobites", "Permian plants", "Cretaceous ammonites"], 0, "Siwalik molasse (~18–1 Ma) preserves rich mammalian faunas and hominoids like Sivapithecus.")

S = "Igneous Petrology"
q(S, "In Bowen's reaction series, the first mineral to crystallise in the discontinuous branch is", ["olivine", "quartz", "biotite", "amphibole"], 0, "Discontinuous series: olivine → pyroxene → amphibole → biotite; continuous: Ca-plagioclase → Na-plagioclase.")
q(S, "A rock with >90% mafic minerals (olivine + pyroxene) and essentially no feldspar is", ["ultramafic (e.g., peridotite)", "felsic", "intermediate", "alkaline syenite"], 0, "Peridotite/dunite/pyroxenite have colour index >90 — ultramafic.")
q(S, "Ophitic texture refers to", ["plagioclase laths enclosed by larger pyroxene crystals", "glassy groundmass", "aligned feldspar laths", "graphic intergrowth of quartz and K-feldspar"], 0, "Ophitic/sub-ophitic textures are typical of dolerites and gabbros.")
q(S, "The dominant rock of the Deccan Traps is", ["tholeiitic basalt", "rhyolite", "andesite", "phonolite"], 0, "Deccan lavas are chiefly tholeiitic flood basalts with minor picrite and alkaline rocks near the margins.")
q(S, "Charnockite is", ["an orthopyroxene-bearing granitoid of granulite-facies affinity", "a quartz-rich sandstone", "an olivine basalt", "a mica schist"], 0, "Charnockite (hypersthene granite) is widespread in the Eastern Ghats and southern granulite terrain.")
q(S, "Pegmatites are typically the product of", ["late-stage, volatile-rich residual magma", "rapid chilling of lava", "high-grade metamorphism of shale", "sedimentary cementation"], 0, "Volatile-rich residual melts yield very coarse crystals and incompatible-element minerals (beryl, Li, Nb–Ta).")
q(S, "Which pair represents the plutonic and volcanic equivalents of the same composition?", ["Granite – Rhyolite", "Gabbro – Andesite", "Diorite – Basalt", "Syenite – Dacite"], 0, "Granite↔rhyolite; diorite↔andesite; gabbro↔basalt; syenite↔trachyte.")
q(S, "Kimberlites are important because they", ["are the principal primary host rock of diamonds", "form large lava plateaus", "host chromite", "are Palaeogene coal-bearing rocks"], 0, "Kimberlite (and lamproite) pipes transport diamonds from >150 km depth; e.g., Wajrakarur, Panna, Majhgawan.")
q(S, "Layered igneous intrusions form chromite seams mainly through", ["gravitational crystal settling and magma mixing during fractional crystallisation", "weathering", "metasomatism by seawater", "sedimentary sorting"], 0, "Chromitite layers (e.g., Sukinda, Bushveld) form by crystal accumulation/mixing in differentiating ultramafic–mafic magma chambers.")
q(S, "Porphyritic texture indicates", ["two stages of cooling: slow (phenocrysts) then fast (groundmass)", "very slow uniform cooling", "metamorphic recrystallisation", "deposition from water"], 0, "Phenocrysts grow slowly at depth; the fine/glassy groundmass forms on eruption or shallow emplacement.")

S = "Sedimentology"
q(S, "Graded bedding (coarse at base, fine at top) is most typical of", ["turbidity current deposits", "aeolian dunes", "fluvial point bars", "evaporites"], 0, "Graded beds (Bouma 'a' division) form as a waning turbidity current drops progressively finer sediment.")
q(S, "Herringbone cross-stratification indicates", ["bidirectional (tidal) currents", "aeolian deposition", "glacial deposition", "deep-sea turbidites"], 0, "Opposed foreset dips in successive sets record reversing ebb–flood tidal flows.")
q(S, "On the Wentworth scale, sand ranges from", ["1/16 mm to 2 mm", "2 to 64 mm", "1/256 to 1/16 mm", "0.5 to 4 mm"], 0, "Clay <1/256 mm; silt 1/256–1/16; sand 1/16–2; granule 2–4; pebble 4–64 mm.")
q(S, "A rock composed mostly of quartz grains with <15% matrix and >95% quartz is", ["quartz arenite", "greywacke", "arkose", "litharenite"], 0, "Quartz arenite = mature sandstone; arkose has >25% feldspar; greywacke has >15% matrix.")
q(S, "Dolomitisation of limestone commonly results in", ["increased porosity due to volume reduction", "decreased porosity", "formation of chert nodules only", "complete silicification"], 0, "Replacement of calcite by dolomite involves ~12–13% volume decrease, often creating intercrystalline porosity (good reservoirs).")
q(S, "Mud cracks and raindrop imprints indicate", ["subaerial exposure", "deep-marine deposition", "glacial deposition", "high-energy surf"], 0, "Desiccation features form when wet mud dries in air—floodplains, tidal flats, playa lakes.")
q(S, "A Bouma sequence describes", ["the ideal vertical succession of a turbidite bed", "a deltaic coarsening-upward cycle", "an aeolian dune set", "a reef facies"], 0, "Bouma divisions Ta (graded) → Tb (parallel lamination) → Tc (ripple) → Td (laminated silt) → Te (pelite).")
q(S, "Placer deposits form by", ["mechanical concentration of dense, resistant minerals by flowing water/wind", "chemical precipitation from brines", "magmatic segregation", "hydrothermal replacement"], 0, "Gold, cassiterite, monazite, ilmenite (e.g., Chhatrapur beach sands, Odisha) concentrate in placers.")

S = "Metamorphic Petrology"
q(S, "The index mineral sequence of Barrovian metamorphism in pelites is", ["chlorite – biotite – garnet – staurolite – kyanite – sillimanite", "sillimanite – kyanite – garnet – chlorite", "andalusite – cordierite – chlorite", "glaucophane – lawsonite – jadeite"], 0, "Barrow's zones (Scottish Highlands) mark increasing medium-P/T grade.")
q(S, "Blueschist facies indicates", ["high pressure and low temperature (subduction zones)", "low pressure, high temperature", "burial under thick lava", "contact metamorphism"], 0, "Glaucophane + lawsonite form at high P/low T, typical of subducted oceanic crust.")
q(S, "Granulite facies is characterised by", ["anhydrous assemblages such as orthopyroxene + plagioclase ± garnet", "abundant chlorite and muscovite", "zeolites", "serpentine"], 0, "High T (>700–750 °C) dehydrates micas/amphiboles; orthopyroxene appears (charnockite, khondalite, two-pyroxene granulite).")
q(S, "Which Al₂SiO₅ polymorph is stable at low pressure–high temperature?", ["andalusite", "kyanite", "sillimanite", "mullite"], 0, "Andalusite: low P; kyanite: high P/low–moderate T; sillimanite: high T.")
q(S, "Hornfels forms by", ["contact metamorphism adjacent to igneous intrusions", "regional metamorphism", "dynamic metamorphism along faults", "weathering"], 0, "Hornfels is a hard, fine-grained, non-foliated rock of thermal aureoles.")
q(S, "Mylonite is produced by", ["ductile shearing with grain-size reduction in shear zones", "contact heating", "burial", "hydrothermal alteration"], 0, "Mylonites show strong foliation, porphyroclasts and dynamic recrystallisation in ductile fault zones.")
q(S, "Marble is the metamorphic equivalent of", ["limestone/dolostone", "sandstone", "shale", "basalt"], 0, "Quartzite ← sandstone; slate/phyllite/schist ← shale; amphibolite ← basalt.")
q(S, "Metamorphic rocks of the Eastern Ghats record peak conditions of", ["ultra-high temperature granulite facies (900–1000 °C)", "greenschist facies", "blueschist facies", "zeolite facies"], 0, "EGMB Mg–Al granulites with sapphirine + quartz and spinel + quartz indicate UHT metamorphism (~950–1000 °C, 8–10 kbar).")
q(S, "Porphyroblasts with S-shaped inclusion trails indicate", ["syn-tectonic growth with rotation", "post-tectonic static growth", "igneous origin", "sedimentary origin"], 0, "Snowball garnets record rotation during growth in a shear regime; straight trails continuous with external foliation suggest post-tectonic growth.")
q(S, "ACF and AKF diagrams are used to represent", ["mineral assemblages of metamorphic facies", "igneous differentiation", "sandstone maturity", "groundwater chemistry"], 0, "Eskola's ACF/AKF triangular plots show compatible mineral assemblages at given P–T.")

S = "Rock Mechanics"
q(S, "Rock Quality Designation (RQD) is the", ["percentage of core pieces ≥10 cm in a core run", "number of joints per metre", "uniaxial compressive strength", "ratio of P- to S-wave velocity"], 0, "RQD = Σ(lengths of intact pieces ≥100 mm)/total run length × 100; >90% = excellent rock.")
q(S, "Uniaxial compressive strength (UCS) of a rock is determined by", ["loading a cylindrical specimen axially to failure without confining pressure", "point-load test only", "Schmidt hammer only", "measuring porosity"], 0, "UCS test on cores (L/D ≈ 2–2.5) gives σc; granite ~100–250 MPa, shale ~10–50 MPa.")
q(S, "Poisson's ratio is", ["lateral strain / axial strain", "stress / strain", "shear stress / shear strain", "volumetric strain"], 0, "ν = −ε_lateral/ε_axial; typically 0.1–0.35 for rocks.")
q(S, "In the Hoek–Brown criterion, the parameter GSI stands for", ["Geological Strength Index", "Geotechnical Stability Index", "Ground Slope Indicator", "Granular Soil Index"], 0, "GSI characterises rock-mass structure and surface condition for estimating rock-mass strength.")
q(S, "Effective stress in a saturated rock mass equals", ["total stress minus pore-water pressure", "total stress plus pore pressure", "pore pressure alone", "shear stress"], 0, "Terzaghi: σ' = σ − u; rising pore pressure reduces effective stress and shear strength (triggers slope failures).")
q(S, "The Brazilian test measures", ["indirect tensile strength", "compressive strength", "shear strength of joints", "permeability"], 0, "A disc loaded diametrically fails in tension across the loaded diameter; σt = 2P/(πDt).")

S = "Groundwater Hydrology"
q(S, "Specific yield of an aquifer is", ["the volume of water that drains by gravity per unit volume of aquifer", "total porosity", "water retained against gravity", "hydraulic conductivity"], 0, "Porosity = specific yield + specific retention; sand Sy ≈ 20–30%, clay very low.")
q(S, "Darcy's law states that discharge through porous media is proportional to", ["the hydraulic gradient and cross-sectional area", "the square of the gradient", "temperature only", "grain size only"], 0, "Q = −K·A·(dh/dl); K = hydraulic conductivity.")
q(S, "A confined aquifer differs from an unconfined one in that", ["it is bounded above by an aquitard and its water is under pressure above the aquifer top", "it has a water table", "it is always shallower", "it cannot be pumped"], 0, "Confined (artesian) aquifers have a potentiometric surface above the aquifer top; unconfined aquifers have a free water table.")
q(S, "Transmissivity equals", ["hydraulic conductivity × saturated thickness", "porosity × thickness", "specific yield × area", "storativity / thickness"], 0, "T = K·b (m²/day); it describes the aquifer's ability to transmit water across its full thickness.")
q(S, "In hard-rock terrains of Odisha (granite, khondalite, charnockite), groundwater occurs mainly in", ["the weathered zone and fractured bedrock", "primary intergranular pores", "karst caverns", "lava tubes"], 0, "Crystalline rocks have negligible primary porosity; secondary porosity (weathering, joints, lineaments) controls yield.")
q(S, "Fluoride contamination of groundwater in parts of Odisha (e.g., Nuapada, Nayagarh) is primarily linked to", ["dissolution of fluoride-bearing minerals (apatite, fluorite, biotite, hornblende) in crystalline rocks", "fertiliser use", "sea-water intrusion", "mining effluent"], 0, "Geogenic fluoride from granitoid/gneissic aquifers under alkaline, Ca-poor conditions exceeds the 1.5 mg/L limit in several districts.")

assert len(Q) == 100, len(Q)

# assemble
sections, questions, start, last = [], [], 0, None
for sec, text, opts, ans, sol in Q:
    if sec != last:
        if last is not None: sections.append({"name": last, "from": start, "to": len(questions)})
        start, last = len(questions), sec
    questions.append({"text": text, "options": opts, "answer": ans, "solution": sol, "marks": 2, "negative": 0.5, "type": "mcq"})
sections.append({"name": last, "from": start, "to": len(questions)})

test = {"id": "opsc-geologist-mock-1", "title": "OPSC Geologist: Mock Test 1 (Paper II – Geology)", "description": "OPSC Geologist written-exam pattern (Paper II, objective): +2 for a correct answer, −0.5 for a wrong one, English medium. 100 questions across all twelve syllabus areas with Odisha-focused geology (Eastern Ghats, Singhbhum craton, Sukinda, Talcher, Mahanadi delta).", "category": "OPSC Geologist", "difficulty": "Moderate", "durationMinutes": 120, "exam": "OPSC Geologist", "sections": sections, "questions": questions}

# write into data/tests.js (replace existing with same id) and tests-index.js
p = os.path.join(ROOT, "data", "tests.js"); src = open(p, encoding="utf-8").read()
arr = json.loads(src[src.index("["):src.rindex("]") + 1])
arr = [t for t in arr if t["id"] != test["id"]] + [test]
open(p, "w", encoding="utf-8").write("// Generated by tools/convert_docx.py / tools/opsc_mock1.py — do not edit by hand.\nwindow.GSA_BUILTIN_TESTS = " + json.dumps(arr, ensure_ascii=False, indent=1) + ";\n")
idx = [{"id": t["id"], "title": t["title"], "description": t.get("description", ""), "category": t.get("category", ""), "difficulty": t.get("difficulty", ""), "durationMinutes": t["durationMinutes"], "questions": len(t["questions"]), "maxMarks": sum(q.get("marks", 1) for q in t["questions"]), "sections": len(t.get("sections", []))} for t in arr]
open(os.path.join(ROOT, "data", "tests-index.js"), "w", encoding="utf-8").write("// Light catalogue of built-in tests (ids/titles/counts) for pages that don't need the questions.\nwindow.GSA_TESTS_INDEX = " + json.dumps(idx, ensure_ascii=False) + ";\n")
print(f"added {test['title']}: {len(questions)} Qs, {len(sections)} sections; bank now {len(arr)} tests")
